export type EconomicsColumnKind = "identity" | "manual" | "calculated" | "api";

export interface EconomicsColumn {
  key: string;
  label: string;
  kind: EconomicsColumnKind;
  editable: boolean;
}

export const manualInputColumns: EconomicsColumn[] = [
  { key: "barcode", label: "ШК", kind: "identity", editable: false },
  { key: "offer_id", label: "Артикул", kind: "identity", editable: false },
  { key: "category_name", label: "Категория", kind: "identity", editable: false },
  { key: "cost_price", label: "Себестоимость, руб.", kind: "manual", editable: true },
  { key: "inbound_logistics_to_warehouse", label: "Логистика до склада, руб.", kind: "manual", editable: true },
  { key: "base_commission_percent", label: "Базовая комиссия, %", kind: "manual", editable: true },
  { key: "product_volume_liters", label: "Объем товара, л", kind: "manual", editable: true },
  { key: "free_acceptance", label: "Бесплатная приемка", kind: "manual", editable: true },
  { key: "buyout_percent", label: "Выкуп, %", kind: "manual", editable: true },
  { key: "non_buyout_percent", label: "Невыкуп, %", kind: "manual", editable: true },
  { key: "return_percent", label: "Возвраты, %", kind: "manual", editable: true },
  { key: "cancel_percent", label: "Отмены, %", kind: "manual", editable: true },
  { key: "delivery_to_pickup_point_cost", label: "Доставка до ПВЗ", kind: "manual", editable: true },
  { key: "express_cost", label: "Затраты на Express", kind: "manual", editable: true },
  { key: "self_purchase_cost", label: "Затраты на самовыкупы", kind: "manual", editable: true },
  { key: "review_points_cost", label: "Отзывы за баллы", kind: "manual", editable: true },
  { key: "paid_storage_cost", label: "Платное хранение", kind: "manual", editable: true },
  { key: "other_expenses", label: "Прочие расходы", kind: "manual", editable: true },
  { key: "confirmed_other_expenses", label: "Подтвержденные прочие расходы", kind: "manual", editable: true },
  { key: "total_drr_percent", label: "Общий ДРР, %", kind: "manual", editable: true },
  { key: "retail_price_without_promo", label: "Розничная цена без акции, руб.", kind: "manual", editable: true },
  { key: "promo_name", label: "Акция", kind: "manual", editable: true },
  { key: "promo_discount_percent", label: "Скидка в акции, %", kind: "manual", editable: true },
  { key: "coinvest_acquiring_percent", label: "Соинвест/эквайринг, %", kind: "manual", editable: true },
  { key: "tax_usn_income_percent", label: "УСН Доходы, %", kind: "manual", editable: true },
  { key: "tax_usn_income_minus_expenses_percent", label: "УСН Доходы-Расходы, %", kind: "manual", editable: true },
  { key: "vat_percent", label: "НДС, %", kind: "manual", editable: true },
  { key: "manufacturer_logistics_lead_weeks", label: "Плечо от производителя, недель", kind: "manual", editable: true },
  { key: "batch_qty", label: "Привезенная партия", kind: "manual", editable: true },
  { key: "sold_qty_month", label: "Продано за месяц", kind: "manual", editable: true },
];

export const calculatedColumns: EconomicsColumn[] = [
  { key: "commission_rub", label: "Комиссия, руб.", kind: "calculated", editable: false },
  { key: "calculated_marker", label: "Расчетная база", kind: "calculated", editable: false },
  { key: "acquiring_rub", label: "Эквайринг, руб.", kind: "calculated", editable: false },
  { key: "ozon_direct_base_logistics_rub", label: "Логистика Ozon базовая, руб.", kind: "calculated", editable: false },
  { key: "nonlocal_logistics_markup_rub", label: "Надбавка за нелокальность", kind: "calculated", editable: false },
  { key: "forecast_direct_logistics_rub", label: "Прогноз прямой логистики", kind: "calculated", editable: false },
  { key: "forecast_reverse_logistics_rub", label: "Прогноз обратной логистики", kind: "calculated", editable: false },
  { key: "acceptance_cost_rub", label: "Стоимость приемки", kind: "calculated", editable: false },
  { key: "pickup_delivery_service_rub", label: "Доставка до ПВЗ, руб.", kind: "calculated", editable: false },
  { key: "total_logistics_rub", label: "Общая логистика, руб.", kind: "calculated", editable: false },
  { key: "ad_cost_per_order_rub", label: "Реклама на заказ, руб.", kind: "calculated", editable: false },
  { key: "ad_cost_per_buyout_rub", label: "Реклама на выкуп, руб.", kind: "calculated", editable: false },
  { key: "tacos_percent", label: "TACoS, %", kind: "calculated", editable: false },
  { key: "total_expenses_rub", label: "Итого расходов, руб.", kind: "calculated", editable: false },
  { key: "confirmed_total_expenses_rub", label: "Подтвержденные расходы, руб.", kind: "calculated", editable: false },
  { key: "marketplace_expense_share_percent", label: "Доля расходов маркетплейса, %", kind: "calculated", editable: false },
  { key: "retail_price_rub", label: "Розничная цена, руб.", kind: "calculated", editable: false },
  { key: "retail_price_with_spp_rub", label: "Розничная цена с СПП, руб.", kind: "calculated", editable: false },
  { key: "gross_profit_rub", label: "Прибыль, руб.", kind: "calculated", editable: false },
  { key: "taxable_profit_for_15_percent_rub", label: "Прибыль для налога 15%, руб.", kind: "calculated", editable: false },
  { key: "tax_usn_income_rub", label: "Налог УСН Доходы, руб.", kind: "calculated", editable: false },
  { key: "tax_usn_income_minus_expenses_rub", label: "Налог УСН Доходы-Расходы, руб.", kind: "calculated", editable: false },
  { key: "vat_rub", label: "НДС, руб.", kind: "calculated", editable: false },
  { key: "total_tax_rub", label: "Итого налог, руб.", kind: "calculated", editable: false },
  { key: "net_profit_per_unit_rub", label: "Чистая прибыль на единицу товара, руб.", kind: "calculated", editable: false },
  { key: "realized_profit_rub", label: "Прибыль от реализованного, руб.", kind: "calculated", editable: false },
  { key: "roi_ratio", label: "ROI", kind: "calculated", editable: false },
  { key: "annual_roi_percent", label: "ROI годовых, %", kind: "calculated", editable: false },
  { key: "margin_percent", label: "Маржинальность, %", kind: "calculated", editable: false },
  { key: "cost_price_share_percent", label: "Доля себестоимости в цене, %", kind: "calculated", editable: false },
];

export const economicsColumns = [...manualInputColumns, ...calculatedColumns];

const importAliases: Array<[string, string]> = [
  ["шк", "barcode"],
  ["barcode", "barcode"],
  ["артикул", "offer_id"],
  ["offer id", "offer_id"],
  ["offer_id", "offer_id"],
  ["категория", "category_name"],
  ["category", "category_name"],
  ["себестоимость, руб.", "cost_price"],
  ["cost price, rub", "cost_price"],
  ["логистика до склада, руб. (кросс-докинг)", "inbound_logistics_to_warehouse"],
  ["inbound logistics, rub", "inbound_logistics_to_warehouse"],
  ["базовая комиссия, %", "base_commission_percent"],
  ["base commission, %", "base_commission_percent"],
  ["объем товара, литр", "product_volume_liters"],
  ["product volume, l", "product_volume_liters"],
  ["условия бесплатной приемки (да/нет)", "free_acceptance"],
  ["free acceptance", "free_acceptance"],
  ["процент выкупа", "buyout_percent"],
  ["buyout, %", "buyout_percent"],
  ["процент невыкупа", "non_buyout_percent"],
  ["non-buyout, %", "non_buyout_percent"],
  ["процент возвратов", "return_percent"],
  ["returns, %", "return_percent"],
  ["процент отмен", "cancel_percent"],
  ["cancellations, %", "cancel_percent"],
  ["доставка до места выдачи", "delivery_to_pickup_point_cost"],
  ["pickup-point delivery", "delivery_to_pickup_point_cost"],
  ["затраты на express", "express_cost"],
  ["express costs", "express_cost"],
  ["затраты на самовыкупы", "self_purchase_cost"],
  ["self-purchase costs", "self_purchase_cost"],
  ["затраты на \"отзывы за баллы\"", "review_points_cost"],
  ["review points costs", "review_points_cost"],
  ["платное хранение", "paid_storage_cost"],
  ["paid storage", "paid_storage_cost"],
  ["прочие расходы", "other_expenses"],
  ["other expenses", "other_expenses"],
  ["прочие расходы (подтвержденные)", "confirmed_other_expenses"],
  ["confirmed other expenses", "confirmed_other_expenses"],
  ["общий дрр от заказа", "total_drr_percent"],
  ["total drr, %", "total_drr_percent"],
  ["розничная цена без акции, руб.", "retail_price_without_promo"],
  ["retail price without promo, rub", "retail_price_without_promo"],
  ["акция", "promo_name"],
  ["promo", "promo_name"],
  ["скидка в акции", "promo_discount_percent"],
  ["promo discount, %", "promo_discount_percent"],
  ["соинвест эквайринг, %", "coinvest_acquiring_percent"],
  ["coinvest/acquiring, %", "coinvest_acquiring_percent"],
  ["ставка налога (усн доходы)", "tax_usn_income_percent"],
  ["usn income tax, %", "tax_usn_income_percent"],
  ["ставка налога (усн доходы-расходы)", "tax_usn_income_minus_expenses_percent"],
  ["usn income-expenses tax, %", "tax_usn_income_minus_expenses_percent"],
  ["ндс", "vat_percent"],
  ["vat, %", "vat_percent"],
  ["логистическое плечо от производителя (недель)", "manufacturer_logistics_lead_weeks"],
  ["manufacturer lead, weeks", "manufacturer_logistics_lead_weeks"],
  ["привезенная партия", "batch_qty"],
  ["batch quantity", "batch_qty"],
  ["продано штук за месяц", "sold_qty_month"],
  ["sold per month", "sold_qty_month"],
];

export const importColumnMap: Record<string, string> = Object.fromEntries([
  ...manualInputColumns.map((column) => [column.label.toLowerCase().trim(), column.key]),
  ...importAliases,
]);

export const editableManualKeys = new Set(
  manualInputColumns.filter((column) => column.editable).map((column) => column.key),
);
