export type EconomicsColumnKind = "identity" | "manual" | "calculated" | "api";

export interface EconomicsColumn {
  key: string;
  label: string;
  kind: EconomicsColumnKind;
  editable: boolean;
}

export const manualInputColumns: EconomicsColumn[] = [
  { key: "barcode", label: "Barcode", kind: "identity", editable: false },
  { key: "offer_id", label: "Offer ID", kind: "identity", editable: false },
  { key: "category_name", label: "Category", kind: "identity", editable: false },
  { key: "cost_price", label: "Cost price, RUB", kind: "manual", editable: true },
  { key: "inbound_logistics_to_warehouse", label: "Inbound logistics, RUB", kind: "manual", editable: true },
  { key: "base_commission_percent", label: "Base commission, %", kind: "manual", editable: true },
  { key: "product_volume_liters", label: "Product volume, l", kind: "manual", editable: true },
  { key: "free_acceptance", label: "Free acceptance", kind: "manual", editable: true },
  { key: "buyout_percent", label: "Buyout, %", kind: "manual", editable: true },
  { key: "non_buyout_percent", label: "Non-buyout, %", kind: "manual", editable: true },
  { key: "return_percent", label: "Returns, %", kind: "manual", editable: true },
  { key: "cancel_percent", label: "Cancellations, %", kind: "manual", editable: true },
  { key: "delivery_to_pickup_point_cost", label: "Pickup-point delivery", kind: "manual", editable: true },
  { key: "express_cost", label: "Express costs", kind: "manual", editable: true },
  { key: "self_purchase_cost", label: "Self-purchase costs", kind: "manual", editable: true },
  { key: "review_points_cost", label: "Review points costs", kind: "manual", editable: true },
  { key: "paid_storage_cost", label: "Paid storage", kind: "manual", editable: true },
  { key: "other_expenses", label: "Other expenses", kind: "manual", editable: true },
  { key: "confirmed_other_expenses", label: "Confirmed other expenses", kind: "manual", editable: true },
  { key: "total_drr_percent", label: "Total DRR, %", kind: "manual", editable: true },
  { key: "retail_price_without_promo", label: "Retail price without promo, RUB", kind: "manual", editable: true },
  { key: "promo_name", label: "Promo", kind: "manual", editable: true },
  { key: "promo_discount_percent", label: "Promo discount, %", kind: "manual", editable: true },
  { key: "coinvest_acquiring_percent", label: "Coinvest/acquiring, %", kind: "manual", editable: true },
  { key: "tax_usn_income_percent", label: "USN income tax, %", kind: "manual", editable: true },
  { key: "tax_usn_income_minus_expenses_percent", label: "USN income-expenses tax, %", kind: "manual", editable: true },
  { key: "vat_percent", label: "VAT, %", kind: "manual", editable: true },
  { key: "manufacturer_logistics_lead_weeks", label: "Manufacturer lead, weeks", kind: "manual", editable: true },
  { key: "batch_qty", label: "Batch quantity", kind: "manual", editable: true },
  { key: "sold_qty_month", label: "Sold per month", kind: "manual", editable: true },
];

export const calculatedColumns: EconomicsColumn[] = [
  { key: "commission_rub", label: "Commission, RUB", kind: "calculated", editable: false },
  { key: "calculated_marker", label: "Calculation basis", kind: "calculated", editable: false },
  { key: "acquiring_rub", label: "Acquiring, RUB", kind: "calculated", editable: false },
  { key: "ozon_direct_base_logistics_rub", label: "Ozon direct base logistics, RUB", kind: "calculated", editable: false },
  { key: "nonlocal_logistics_markup_rub", label: "Nonlocal logistics markup", kind: "calculated", editable: false },
  { key: "forecast_direct_logistics_rub", label: "Forecast direct logistics", kind: "calculated", editable: false },
  { key: "forecast_reverse_logistics_rub", label: "Forecast reverse logistics", kind: "calculated", editable: false },
  { key: "acceptance_cost_rub", label: "Acceptance cost", kind: "calculated", editable: false },
  { key: "pickup_delivery_service_rub", label: "Pickup delivery service", kind: "calculated", editable: false },
  { key: "total_logistics_rub", label: "Total logistics, RUB", kind: "calculated", editable: false },
  { key: "ad_cost_per_order_rub", label: "Ad cost per order", kind: "calculated", editable: false },
  { key: "ad_cost_per_buyout_rub", label: "Ad cost per buyout", kind: "calculated", editable: false },
  { key: "tacos_percent", label: "TACoS, %", kind: "calculated", editable: false },
  { key: "total_expenses_rub", label: "Total expenses, RUB", kind: "calculated", editable: false },
  { key: "confirmed_total_expenses_rub", label: "Confirmed total expenses", kind: "calculated", editable: false },
  { key: "marketplace_expense_share_percent", label: "Marketplace expense share, %", kind: "calculated", editable: false },
  { key: "retail_price_rub", label: "Retail price, RUB", kind: "calculated", editable: false },
  { key: "retail_price_with_spp_rub", label: "Retail price with SPP", kind: "calculated", editable: false },
  { key: "gross_profit_rub", label: "Gross profit, RUB", kind: "calculated", editable: false },
  { key: "taxable_profit_for_15_percent_rub", label: "Taxable profit for 15%", kind: "calculated", editable: false },
  { key: "tax_usn_income_rub", label: "USN income tax, RUB", kind: "calculated", editable: false },
  { key: "tax_usn_income_minus_expenses_rub", label: "USN income-expenses tax, RUB", kind: "calculated", editable: false },
  { key: "vat_rub", label: "VAT, RUB", kind: "calculated", editable: false },
  { key: "total_tax_rub", label: "Total tax, RUB", kind: "calculated", editable: false },
  { key: "net_profit_per_unit_rub", label: "Net profit per unit", kind: "calculated", editable: false },
  { key: "realized_profit_rub", label: "Realized profit", kind: "calculated", editable: false },
  { key: "roi_ratio", label: "ROI", kind: "calculated", editable: false },
  { key: "annual_roi_percent", label: "Annual ROI, %", kind: "calculated", editable: false },
  { key: "margin_percent", label: "Margin, %", kind: "calculated", editable: false },
  { key: "cost_price_share_percent", label: "Cost price share, %", kind: "calculated", editable: false },
];

export const economicsColumns = [...manualInputColumns, ...calculatedColumns];

const importAliases: Array<[string, string]> = [
  ["шк", "barcode"],
  ["barcode", "barcode"],
  ["артикул", "offer_id"],
  ["offer id", "offer_id"],
  ["offer_id", "offer_id"],
  ["категория", "category_name"],
  ["category", "category_name"],
  ["себестоимость, руб.", "cost_price"],
  ["cost price, rub", "cost_price"],
  ["логистика до склада, руб. (кросс-докинг)", "inbound_logistics_to_warehouse"],
  ["inbound logistics, rub", "inbound_logistics_to_warehouse"],
  ["базовая комиссия, %", "base_commission_percent"],
  ["base commission, %", "base_commission_percent"],
  ["объем товара, литр", "product_volume_liters"],
  ["product volume, l", "product_volume_liters"],
  ["условия бесплатной приемки (да/нет)", "free_acceptance"],
  ["free acceptance", "free_acceptance"],
  ["процент выкупа", "buyout_percent"],
  ["buyout, %", "buyout_percent"],
  ["процент невыкупа", "non_buyout_percent"],
  ["non-buyout, %", "non_buyout_percent"],
  ["процент возвратов", "return_percent"],
  ["returns, %", "return_percent"],
  ["процент отмен", "cancel_percent"],
  ["cancellations, %", "cancel_percent"],
  ["доставка до места выдачи", "delivery_to_pickup_point_cost"],
  ["pickup-point delivery", "delivery_to_pickup_point_cost"],
  ["затраты на express", "express_cost"],
  ["express costs", "express_cost"],
  ["затраты на самовыкупы", "self_purchase_cost"],
  ["self-purchase costs", "self_purchase_cost"],
  ["затраты на \"отзывы за баллы\"", "review_points_cost"],
  ["review points costs", "review_points_cost"],
  ["платное хранение", "paid_storage_cost"],
  ["paid storage", "paid_storage_cost"],
  ["прочие расходы", "other_expenses"],
  ["other expenses", "other_expenses"],
  ["прочие расходы (подтвержденные)", "confirmed_other_expenses"],
  ["confirmed other expenses", "confirmed_other_expenses"],
  ["общий дрр от заказа", "total_drr_percent"],
  ["total drr, %", "total_drr_percent"],
  ["розничная цена без акции, руб.", "retail_price_without_promo"],
  ["retail price without promo, rub", "retail_price_without_promo"],
  ["акция", "promo_name"],
  ["promo", "promo_name"],
  ["скидка в акции", "promo_discount_percent"],
  ["promo discount, %", "promo_discount_percent"],
  ["соинвест эквайринг, %", "coinvest_acquiring_percent"],
  ["coinvest/acquiring, %", "coinvest_acquiring_percent"],
  ["ставка налога (усн доходы)", "tax_usn_income_percent"],
  ["usn income tax, %", "tax_usn_income_percent"],
  ["ставка налога (усн доходы-расходы)", "tax_usn_income_minus_expenses_percent"],
  ["usn income-expenses tax, %", "tax_usn_income_minus_expenses_percent"],
  ["ндс", "vat_percent"],
  ["vat, %", "vat_percent"],
  ["логистическое плечо от производителя (недель)", "manufacturer_logistics_lead_weeks"],
  ["manufacturer lead, weeks", "manufacturer_logistics_lead_weeks"],
  ["привезенная партия", "batch_qty"],
  ["batch quantity", "batch_qty"],
  ["продано штук за месяц", "sold_qty_month"],
  ["sold per month", "sold_qty_month"],
];

export const importColumnMap: Record<string, string> = Object.fromEntries([
  ...manualInputColumns.map((column) => [column.label.toLowerCase().trim(), column.key]),
  ...importAliases,
]);

export const editableManualKeys = new Set(
  manualInputColumns.filter((column) => column.editable).map((column) => column.key),
);
